# -*- coding: utf-8 -*-
"""model.pkl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZyY59NY9lbBAK3G1FUiX9Gk0hZLiiQf
"""

from sklearn.linear_model import LogisticRegression
import numpy as np

# Example data
X = np.array([[0, 1], [1, 0], [1, 0], [0, 1]])  # One-hot encoded gender
y = [0, 1, 1, 0]

# Fit model
model = LogisticRegression()
model.fit(X, y)

# Save model to model.pkl
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)